# Generated by Django 3.1.1 on 2025-01-06 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel_app', '0003_auto_20240501_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Assessment',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
    ]
